package soot.jimple.infoflow;

/**
 * Enumeration containing the phases of a data flow analysis
 * 
 * @author Steven Arzt
 */
public enum AnalysisPhase {

	/**
	 * Taints are being propagated while solving the IFDS problem
	 */
	TAINT_PROPAGATION,

	/**
	 * Paths from source to sink are reconstructed from the taint graph generated by
	 * the IFDS problem
	 */
	PATH_RECONSTRUCTION

}
